const LANG_EN = {
  app_title: "Jet Lag Maps",
  app_subtitle: "Hide & Seek Map Tools",
  unit_km: "km",
  unit_mi: "mi",
  sec_city: "City",
  sec_layers: "Layers",
  sec_radius: "Radius Tool",
  sec_measure: "Distance & Direction",
  city_placeholder: "e.g. London, Berlin …",
  btn_search: "Search",
  lyr_cityboundary: "City Boundary",
  lyr_plz: "Postal Codes",
  lyr_hospitals: "Hospitals",
  lyr_stations: "Train & Tram Stations",
  lyr_attractions: "Attractions",
  lyr_parks: "City Parks",
  lyr_greenspaces: "Green Spaces",
  lyr_shopping: "Shopping Centres",
  lyr_busstops: "Bus Stops",
  lyr_cinema: "Cinemas",
  lyr_zoo: "Zoos",
  lyr_townhall: "Town Halls",
  lyr_coastline: "Coastline",
  lyr_water: "Water Bodies",
  lyr_aquarium: "Aquariums",
  lyr_library: "Libraries",
  lyr_golf: "Golf Courses",
  lyr_stadium: "Stadiums",
  lyr_embassy: "Embassies",
  lyr_consulate: "Consulates",
  lyr_cemetery: "Cemeteries",
  lyr_swimmingpool: "Swimming Pools",
  lyr_police: "Police Stations",
  lyr_firestation: "Fire Stations",
  lyr_airports: "Airports",
  lyr_airfields: "Airfields",
  lyr_fastfood: "Fast Food Chains",
  lyr_museum: "Museums",
  lyr_amusementpark: "Amusement Parks",
  btn_clear_layers: "Remove all layers",
  sec_busroutes: "Bus Routes",
  busroute_hint: "Enter line number (e.g. 305)",
  btn_add_route: "Draw",
  btn_clear_routes: "Remove all routes",
  lbl_line: "Line",
  status_loading_route: "Loading route {0} …",
  status_route_loaded: "Route {0} loaded ({1} variant(s))",
  status_route_not_found: "Route {0} not found",
  status_route_duplicate: "Route {0} already drawn",
  status_route_no_geom: "No geometry for route {0}",
  err_busroute: "Bus route {0}:\n\n{1}",
  stop_lines_loading: "Loading lines…",
  stop_lines_none: "No line info",
  stop_lines_error: "Error loading lines",
  coord_hint: "↖ Click on the map to set the centre",
  tab_single: "Single",
  tab_interval: "Interval",
  lbl_radius: "{0} radius",
  lbl_step: "{0} step,",
  lbl_rings: "rings",
  btn_draw: "Draw",
  manual_hint: "Or enter coordinates manually:",
  lat_placeholder: "Lat e.g. 53.1435",
  lng_placeholder: "Lon e.g. 8.2146",
  btn_use_coords: "Use coordinates",
  btn_clear_radii: "Remove all radii",
  bnd_zones: "Zones",
  bnd_admin: "Admin Levels",
  lyr_admin1: "Level 1 (Suburb)",
  lyr_admin2: "Level 2 (City)",
  lyr_admin3: "Level 3 (County)",
  lyr_admin4: "Level 4 (State)",
  fab_boundary_title: "Zones & Admin Levels",
  fab_layer_title: "POI Layers",
  err_no_geojson: "No polygon data available",
  sec_admin: "Admin Division",
  admin_hint:
    "Set two points on the map to see if they share the same admin levels.",
  btn_admin_start: "Start checker",
  btn_admin_stop: "Cancel",
  btn_admin_clear: "Clear result",
  status_admin_a: "Click point A on the map",
  status_admin_b: "Click point B on the map",
  status_admin_loading: "Loading admin data …",
  status_admin_done: "Comparison complete",
  admin_loading: "Loading …",
  measure_hint: "Click two points on the map – A then B.",
  btn_measure_start: "Start measuring",
  btn_measure_stop: "Cancel",
  btn_clear_meas: "Clear measurement",
  style_label: "Map style",
  style_osm: "OSM Standard",
  style_light: "☀️ Light (Positron)",
  style_dark: "🌑 Dark",
  style_voyager: "🧭 Voyager",
  style_satellite: "🛰 Satellite",
  style_opnv: "🚌 Public Transport",
  color_mode_label: "Colour palette",
  color_mode_default: "Default",
  color_mode_cb: "Colour-blind safe",
  fab_print_title: "Print / Save as PDF",
  fab_style_title: "Choose map style",
  fab_permalink_title: "Copy link",
  status_ready: "Ready",
  status_searching: "Searching city …",
  status_not_found: "City not found",
  status_err: "Error: {0}",
  status_map: "Map: {0}",
  status_loading: "Loading {0} …",
  status_loaded: "{0} loaded",
  status_err_popup: "Error – see popup for details",
  status_point_a: "Click point A on the map",
  status_point_b: "Click point B on the map",
  status_meas_done: "Measurement complete",
  status_center: "Centre: {0}",
  status_no_point: "Click a point on the map first",
  status_bad_radius: "Invalid radius",
  status_bad_interval: "Invalid interval values",
  status_radius_drawn: "Radius drawn: {0}",
  status_interval_drawn: "Interval drawn: {0} rings × {1}",
  status_bad_coords: "Invalid coordinates",
  ri_radius: "{0} radius",
  ri_interval: "{0}× {1} interval",
  compass_dirs: "N,NE,E,SE,S,SW,W,NW",
  plz_label: "Postcode {0}",
  err_title: "Loading error",
  err_copy: "📋 Copy error text",
  err_copied: "✅ Copied!",
  err_copy_fail: "✗ Copy failed",
  err_layer: "Layer: {0}\n\n{1}",
  sec_nearest_poi: "Nearest POIs",
  nearest_poi_hint: "Click a point on the map to see distances to nearby POIs.",
  btn_np_start: "Find nearest POIs",
  btn_np_stop: "Cancel",
  btn_np_clear: "Clear",
  status_np_click: "Click a point on the map",
  sec_nearest: "Same Nearest",
  nearest_hint:
    "Select layers in the layer panel. Click 📍 → then click on the map to set a point, or type coordinates directly.",
  btn_nc_start: "Check",
  btn_nc_stop: "Cancel",
  btn_nc_clear: "Clear",
  nc_loading: "Loading…",
  nc_same: "Same nearest – MATCH",
  nc_diff: "Different nearest – NO MATCH",
  nc_no_data: "No POIs found nearby",
  nc_no_layers: "No layers active. Please select layers in the 📍 panel first.",
  nc_need_points: "Please enter both coordinates (A and B).",
  nc_pick_title: "Click on the map",
  status_nc_a: "Click point A on the map",
  status_nc_b: "Click point B on the map",
  sec_changelog: "Changelog",
  changelog_last: "Last update:",
  sec_questions: "Tentacles",
  btn_add_question: "+ Add Tentacle",
  tent_kilometers: "Kilometers",
  tent_miles: "Miles",
  tent_location_btn: "📍 Location",
  tent_set_center: "– click to set center –",
  tent_select_poi: "– Set center first –",
  tent_select: "– Select –",
  tent_loading: "Loading…",
  tent_error: "Error loading",
  tent_status_loading: "Loading {0}…",
  tent_status_found: "{0} {1} found",
  tent_status_pick: "Click on the map to set the tentacle center point",
};
